/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tudien_ver2;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author MyPC
 */
public class Main extends javax.swing.JFrame {

    DictionaryManagement dicMana = new DictionaryManagement();
    DefaultListModel listModel = new DefaultListModel();

    /**
     * Creates new form Main
     *
     * @throws java.io.IOException
     */
    public Main() throws IOException {
        initComponents();
        dicMana.insertFromFile();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        listWordTarget = new javax.swing.JList<>();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        searchArea = new javax.swing.JTextField();
        searchButton = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        addWord = new javax.swing.JButton();
        change = new javax.swing.JButton();
        api = new javax.swing.JButton();
        voice = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        wordExplainAria = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        cb1 = new javax.swing.JComboBox<>();
        cb2 = new javax.swing.JComboBox<>();
        JTF1 = new javax.swing.JTextField();
        JTF2 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        translate = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Dictionary");
        setBackground(new java.awt.Color(0, 0, 0));
        setFont(new java.awt.Font(".VnArabia", 0, 15)); // NOI18N
        setForeground(java.awt.Color.white);

        listWordTarget.setBackground(new java.awt.Color(51, 51, 255));
        listWordTarget.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        listWordTarget.setForeground(new java.awt.Color(255, 255, 0));
        listWordTarget.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
                listWordTargetAncestorMoved(evt);
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                listWordTargetAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        listWordTarget.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                listWordTargetKeyReleased(evt);
            }
        });
        listWordTarget.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listWordTargetValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(listWordTarget);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\MyPC\\Desktop\\image\\f38c4e896de0a55914f040eee0535c0b (1).jpg")); // NOI18N
        jLabel1.setText("jLabel1");

        searchArea.setBackground(new java.awt.Color(104, 104, 104));
        searchArea.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        searchArea.setForeground(new java.awt.Color(204, 204, 204));
        searchArea.setText("Nhập một từ");
        searchArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchAreaActionPerformed(evt);
            }
        });
        searchArea.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchAreaKeyReleased(evt);
            }
        });

        searchButton.setIcon(new javax.swing.ImageIcon("C:\\Users\\MyPC\\Desktop\\image\\if_013_MagnifyingGlass_183520 (1).png")); // NOI18N
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        delete.setIcon(new javax.swing.ImageIcon("C:\\Users\\MyPC\\Desktop\\image\\if_trash_bin_1370026.png")); // NOI18N
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });

        addWord.setIcon(new javax.swing.ImageIcon("C:\\Users\\MyPC\\Desktop\\image\\if_add_126583 (1).png")); // NOI18N
        addWord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addWordActionPerformed(evt);
            }
        });

        change.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        change.setIcon(new javax.swing.ImageIcon("C:\\Users\\MyPC\\Desktop\\image\\if_arrow_circle_double_11450.png")); // NOI18N
        change.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeActionPerformed(evt);
            }
        });

        api.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        api.setText("Translate-API");
        api.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apiActionPerformed(evt);
            }
        });

        voice.setIcon(new javax.swing.ImageIcon("C:\\Users\\MyPC\\Desktop\\image\\if_volume-24_103167 (1).png")); // NOI18N
        voice.setText("US");
        voice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voiceActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\MyPC\\Desktop\\image\\if_volume-24_103167 (1).png")); // NOI18N
        jButton1.setText("UK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(searchArea, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(searchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addWord, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(delete)
                .addGap(5, 5, 5)
                .addComponent(voice)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(change, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(api, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(717, 717, 717))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(252, 252, 252)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(change, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(searchButton, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
                            .addComponent(searchArea)
                            .addComponent(addWord, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(delete, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(voice, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(api, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        wordExplainAria.setBackground(new java.awt.Color(51, 51, 255));
        wordExplainAria.setColumns(20);
        wordExplainAria.setFont(new java.awt.Font("Monospaced", 0, 17)); // NOI18N
        wordExplainAria.setForeground(new java.awt.Color(255, 255, 0));
        wordExplainAria.setRows(5);
        jScrollPane1.setViewportView(wordExplainAria);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 526, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 476, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Dịch Từ", jPanel2);

        cb1.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        cb1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "English", "Vietnamese" }));
        cb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb1ActionPerformed(evt);
            }
        });

        cb2.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        cb2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "English", "Vietnamese" }));
        cb2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb2ActionPerformed(evt);
            }
        });

        JTF1.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        JTF1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        JTF1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTF1ActionPerformed(evt);
            }
        });
        JTF1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                JTF1KeyReleased(evt);
            }
        });

        JTF2.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        JTF2.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jButton2.setIcon(new javax.swing.ImageIcon("C:\\Users\\MyPC\\Desktop\\image\\if_volume-24_103167.png")); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        translate.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        translate.setText("Translate");
        translate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                translateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(cb1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(translate)
                        .addGap(87, 87, 87)
                        .addComponent(cb2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(JTF1)
                        .addGap(29, 29, 29)
                        .addComponent(JTF2, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(232, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(230, 230, 230))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(translate, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JTF1, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JTF2, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Translate-API", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 885, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 359, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 531, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2)
                    .addComponent(jTabbedPane1))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void listWordTargetValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listWordTargetValueChanged

        int i = 0;
        while (i < dicMana.list.size()) {
            if (listWordTarget.getSelectedValue().equals(dicMana.list.get(i).getWordTarget())) {
                wordExplainAria.setText(dicMana.list.get(i).getWordExplain());
            }
            i++;
        }
        searchArea.setText(listWordTarget.getSelectedValue());
    }//GEN-LAST:event_listWordTargetValueChanged

    private void listWordTargetAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_listWordTargetAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_listWordTargetAncestorAdded

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        voiceUK ukabc = new voiceUK("ukdjfaiwejf");
        ukabc.say(searchArea.getText());
    }//GEN-LAST:event_jButton1ActionPerformed

    private void voiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voiceActionPerformed

        voice vc = new voice("ducminh");
        vc.say(searchArea.getText());
    }//GEN-LAST:event_voiceActionPerformed

    private void apiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apiActionPerformed

        API translate = new API();
        String we = "";
        try {
            we = translate.callTranslate("en", "vi", searchArea.getText());
        } catch (Exception ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }
        wordExplainAria.setText(we);
    }//GEN-LAST:event_apiActionPerformed

    private void changeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeActionPerformed
        // TODO add your handling code here:
        JTextField mean = new JTextField();
        String str;
        Object[] message = {
            " Nhập nghĩa mới ", mean,};
        int option = JOptionPane.showConfirmDialog(null, message, "Change explain", JOptionPane.OK_CANCEL_OPTION);
        if (option == JOptionPane.OK_OPTION) {
            if (mean.getText().equals("")==false) {
                str = mean.getText();
                dicMana.changeWord(searchArea.getText(), str);
                wordExplainAria.setText(mean.getText());
                JOptionPane.showMessageDialog(null, "Done!");
            } else {
                JOptionPane.showMessageDialog(null, "Could not change explain");
            }

        }
    }//GEN-LAST:event_changeActionPerformed

    private void addWordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addWordActionPerformed
        // TODO add your handling code here:
        String wt, we;
        JTextField textWT = new JTextField();
        JTextField textWE = new JTextField();
        Object[] message = {
            "Input the new word: ", textWT,
            "Input word's explain: ", textWE,};
        int option = JOptionPane.showConfirmDialog(null, message, "Input new word", JOptionPane.OK_CANCEL_OPTION);
        if (option == JOptionPane.OK_OPTION) {
            boolean check = false;
            if (!textWT.getText().equals("") && !textWE.getText().equals("")) {
                wt = dicMana.chuanhoa(textWT.getText());
                we = dicMana.chuanhoa(textWE.getText());
         
                int i = 0;
                while(i < dicMana.list.size()){
                    if (wt.equals(dicMana.list.get(i).getWordTarget())) {
                        JOptionPane.showMessageDialog(null, "Từ đã tồn tại!");
                        check = true;
                        break;
                    }
                    i++;
                }
                
                if (check == false) {
                    Word words = new Word(wt, we);
                    dicMana.list.add(words);
                    listModel.addElement(wt);
                    listWordTarget.setModel(listModel);

                    JOptionPane.showMessageDialog(null, "Done!");
                }
            }

        } else if (textWT.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Please input word!");
            textWT.requestFocus();
        } else {
            JOptionPane.showMessageDialog(null, "Please input explain!");
            textWE.requestFocus();
        }
    }//GEN-LAST:event_addWordActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        // TODO add your handling code here:

        String str = searchArea.getText();
        dicMana.deleteWord(str);
        listModel.remove(listWordTarget.getSelectedIndex());
        listWordTarget.setModel(listModel);
    }//GEN-LAST:event_deleteActionPerformed

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        // TODO add your handling code here:
        boolean check = false;
        int i = 0;
        while (i < dicMana.list.size()) {
            if (dicMana.chuanhoa(searchArea.getText()).equals(dicMana.list.get(i).getWordTarget())) {
                wordExplainAria.setText(dicMana.list.get(i).getWordExplain());
                check = true;
            }
            i++;
        }
        if (check == false) {
            JOptionPane.showMessageDialog(null, "Word Cannot Found!");
        }
    }//GEN-LAST:event_searchButtonActionPerformed

    private void searchAreaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchAreaKeyReleased
        // TODO add your handling code here:
        try {
            DefaultListModel listModel1 = new DefaultListModel();
            int i = 0;
            while(i < dicMana.list.size()){
                if (dicMana.list.get(i).getWordTarget().startsWith(searchArea.getText())) {
                    listModel1.addElement(dicMana.list.get(i).getWordTarget());
                }
                i++;
            }
            listWordTarget.setModel(listModel1);

        } catch (NullPointerException e) {
            System.out.println("Error: " + e.getMessage());
        }
    }//GEN-LAST:event_searchAreaKeyReleased

    private void searchAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchAreaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchAreaActionPerformed

    private void JTF1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTF1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTF1ActionPerformed

    private void JTF1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JTF1KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_JTF1KeyReleased

    private void cb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb1ActionPerformed

    private void cb2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb2ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        voice api = new voice("abc");
        api.say(JTF1.getText());
    }//GEN-LAST:event_jButton2ActionPerformed

    private void translateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_translateActionPerformed
        // TODO add your handling code here:
        API translate = new API();
        String s = "";
        try {
            String to, from;
            to = cb1.getSelectedItem().toString();
            from = cb2.getSelectedItem().toString();
            if (to.equals("Vietnamese")) {
                to = "vi";
            } else {
                to = "en";
            }
            if (from.equals("Vietnamese")) {
                from = "vi";
            } else {
                from = "en";
            }
            s = translate.callTranslate(to, from, JTF1.getText());
        } catch (Exception ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }
        JTF2.setText(s);
    }//GEN-LAST:event_translateActionPerformed

    private void listWordTargetAncestorMoved(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_listWordTargetAncestorMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_listWordTargetAncestorMoved

    private void listWordTargetKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_listWordTargetKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_listWordTargetKeyReleased

    public static void main(String args[]) {

        java.awt.EventQueue.invokeLater(() -> {
            try {
                new Main().setVisible(true);
            } catch (IOException ex) {
                Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField JTF1;
    private javax.swing.JTextField JTF2;
    private javax.swing.JButton addWord;
    private javax.swing.JButton api;
    private javax.swing.JComboBox<String> cb1;
    private javax.swing.JComboBox<String> cb2;
    private javax.swing.JButton change;
    private javax.swing.JButton delete;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JList<String> listWordTarget;
    private javax.swing.JTextField searchArea;
    private javax.swing.JButton searchButton;
    private javax.swing.JButton translate;
    private javax.swing.JButton voice;
    private javax.swing.JTextArea wordExplainAria;
    // End of variables declaration//GEN-END:variables
}
